services:
  visa-stat-app-frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visa-stat-app-frontend
    ports:
      - '4173:4173'

  visa-stat-app-backend:
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: visa-stat-app-backend
    ports:
      - '3001:3001'